# Generated by Django 4.0.3 on 2022-04-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0003_alter_campus_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
