# Generated by Django 4.0.3 on 2022-05-17 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=255)),
                ('listed', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('location', models.CharField(max_length=255)),
                ('registerLink', models.CharField(max_length=255)),
                ('image', models.CharField(blank=True, max_length=255)),
                ('eventStart', models.DateTimeField()),
                ('eventEnd', models.DateTimeField()),
                ('lastUpdate', models.DateTimeField(auto_now=True)),
                ('timeCreated', models.DateTimeField(auto_now_add=True)),
                ('listed', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('listed', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('listed', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=255)),
                ('image', models.CharField(blank=True, max_length=255)),
                ('menuLink', models.CharField(blank=True, max_length=255)),
                ('bookingLink', models.CharField(blank=True, max_length=255)),
                ('listed', models.BooleanField(default=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tafe.campus')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('S', 'Student'), ('P', 'Parent/Guardian'), ('T', 'Teacher'), ('CS', 'Career Starter'), ('CC', 'Career Changer')], default='S', max_length=2)),
                ('timeCreated', models.DateTimeField(auto_now_add=True)),
                ('notificationToken', models.CharField(blank=True, max_length=255)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tafe.campus')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tafe.industry')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tafe.region')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monOpen', models.TimeField()),
                ('monClose', models.TimeField()),
                ('tueOpen', models.TimeField()),
                ('tueClose', models.TimeField()),
                ('wedOpen', models.TimeField()),
                ('wedClose', models.TimeField()),
                ('thurOpen', models.TimeField()),
                ('thurClose', models.TimeField()),
                ('friOpen', models.TimeField()),
                ('friClose', models.TimeField()),
                ('satOpen', models.TimeField()),
                ('satClose', models.TimeField()),
                ('sunOpen', models.TimeField()),
                ('sunClose', models.TimeField()),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tafe.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('I', 'Industry'), ('R', 'Region'), ('C', 'Campus')], default='C', max_length=1)),
                ('title', models.CharField(max_length=255)),
                ('body', models.CharField(max_length=255)),
                ('data', models.TextField()),
                ('sendTime', models.DateTimeField()),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tafe.campus')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tafe.industry')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tafe.region')),
            ],
        ),
        migrations.CreateModel(
            name='CampusHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monOpen', models.TimeField()),
                ('monClose', models.TimeField()),
                ('tueOpen', models.TimeField()),
                ('tueClose', models.TimeField()),
                ('wedOpen', models.TimeField()),
                ('wedClose', models.TimeField()),
                ('thurOpen', models.TimeField()),
                ('thurClose', models.TimeField()),
                ('friOpen', models.TimeField()),
                ('friClose', models.TimeField()),
                ('satOpen', models.TimeField()),
                ('satClose', models.TimeField()),
                ('sunOpen', models.TimeField()),
                ('sunClose', models.TimeField()),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tafe.campus')),
            ],
        ),
        migrations.AddField(
            model_name='campus',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tafe.region'),
        ),
    ]
